# define: nginx::resource::location
#
# This is a legacy resource that will be deprecated in v1.0.0
#
# Please add any additions to nginx::location
define nginx::resource::location (
  $ensure                      = undef,
  $internal                    = undef,
  $location                    = undef,
  $vhost                       = undef,
  $www_root                    = undef,
  $autoindex                   = undef,
  $index_files                 = undef,
  $proxy                       = undef,
  $proxy_redirect              = undef,
  $proxy_read_timeout          = undef,
  $proxy_connect_timeout       = undef,
  $proxy_set_header            = undef,
  $fastcgi                     = undef,
  $fastcgi_param               = undef,
  $fastcgi_params              = undef,
  $fastcgi_script              = undef,
  $fastcgi_split_path          = undef,
  $ssl                         = undef,
  $ssl_only                    = undef,
  $location_alias              = undef,
  $location_allow              = undef,
  $location_deny               = undef,
  $option                      = undef,
  $stub_status                 = undef,
  $raw_prepend                 = undef,
  $raw_append                  = undef,
  $location_custom_cfg         = undef,
  $location_cfg_prepend        = undef,
  $location_cfg_append         = undef,
  $location_custom_cfg_prepend = undef,
  $location_custom_cfg_append  = undef,
  $include                     = undef,
  $try_files                   = undef,
  $proxy_cache                 = undef,
  $proxy_cache_valid           = undef,
  $proxy_method                = undef,
  $proxy_set_body              = undef,
  $auth_basic                  = undef,
  $auth_basic_user_file        = undef,
  $rewrite_rules               = undef,
  $priority                    = undef,
  $mp4                         = undef,
  $flv                         = undef,
) {
  nginx::notice::resources { $name: }

  nginx::location { $name:
    ensure                      => $ensure,
    internal                    => $internal,
    location                    => $location,
    vhost                       => $vhost,
    www_root                    => $www_root,
    autoindex                   => $autoindex,
    index_files                 => $index_files,
    proxy                       => $proxy,
    proxy_redirect              => $proxy_redirect,
    proxy_read_timeout          => $proxy_read_timeout,
    proxy_connect_timeout       => $proxy_connect_timeout,
    proxy_set_header            => $proxy_set_header,
    fastcgi                     => $fastcgi,
    fastcgi_param               => $fastcgi_param,
    fastcgi_params              => $fastcgi_params,
    fastcgi_script              => $fastcgi_script,
    fastcgi_split_path          => $fastcgi_split_path,
    ssl                         => $ssl,
    ssl_only                    => $ssl_only,
    location_alias              => $location_alias,
    location_allow              => $location_allow,
    location_deny               => $location_deny,
    option                      => $option,
    stub_status                 => $stub_status,
    raw_prepend                 => $raw_prepend,
    raw_append                  => $raw_append,
    location_custom_cfg         => $location_custom_cfg,
    location_cfg_prepend        => $location_cfg_prepend,
    location_cfg_append         => $location_cfg_append,
    location_custom_cfg_prepend => $location_custom_cfg_prepend,
    location_custom_cfg_append  => $location_custom_cfg_append,
    include                     => $include,
    try_files                   => $try_files,
    proxy_cache                 => $proxy_cache,
    proxy_cache_valid           => $proxy_cache_valid,
    proxy_method                => $proxy_method,
    proxy_set_body              => $proxy_set_body,
    auth_basic                  => $auth_basic,
    auth_basic_user_file        => $auth_basic_user_file,
    rewrite_rules               => $rewrite_rules,
    priority                    => $priority,
    mp4                         => $mp4,
    flv                         => $flv,
  }
}
