# define: nginx::resource::location
#
# Legacy defined type. Will be removed soon.
define nginx::resource::location (
  $ensure                       = present,
  $internal                     = false,
  $location                     = $name,
  $vhost                        = undef,
  $www_root                     = undef,
  $autoindex                    = undef,
  $index_files                  = [
    'index.html',
    'index.htm',
    'index.php'
  ],
  $proxy                        = undef,
  $proxy_redirect               = $nginx::config::proxy_redirect,
  $proxy_read_timeout           = $nginx::config::proxy_read_timeout,
  $proxy_connect_timeout        = $nginx::config::proxy_connect_timeout,
  $proxy_set_header             = $nginx::config::proxy_set_header,
  $fastcgi                      = undef,
  $fastcgi_param                = undef,
  $fastcgi_params               = "${nginx::config::conf_dir}/fastcgi_params",
  $fastcgi_script               = undef,
  $fastcgi_split_path           = undef,
  $ssl                          = false,
  $ssl_only                     = false,
  $location_alias               = undef,
  $location_allow               = undef,
  $location_deny                = undef,
  $option                       = undef,
  $stub_status                  = undef,
  $raw_prepend                  = undef,
  $raw_append                   = undef,
  $location_custom_cfg          = undef,
  $location_cfg_prepend         = undef,
  $location_cfg_append          = undef,
  $location_custom_cfg_prepend  = undef,
  $location_custom_cfg_append   = undef,
  $try_files                    = undef,
  $proxy_cache                  = false,
  $proxy_cache_valid            = false,
  $proxy_method                 = undef,
  $proxy_set_body               = undef,
  $auth_basic                   = undef,
  $auth_basic_user_file         = undef,
  $rewrite_rules                = [],
  $priority                     = 500,
  $mp4                          = false,
  $flv                          = false,
) {

  notify { '**WARNING**: Usage of the nginx::resource::location defined type will be deprecated soon. Please use nginx::location.': }

  nginx::resource::location { $name:
    ensure                      => $ensure,
    internal                    => $internal,
    location                    => $location,
    vhost                       => $vhost,
    www_root                    => $www_root,
    autoindex                   => $autoindex,
    index_files                 => $index_files,
    proxy                       => $proxy,
    proxy_redirect              => $proxy_redirect,
    proxy_read_timeout          => $proxy_read_timeout,
    proxy_connect_timeout       => $proxy_connect_timeout,
    proxy_set_header            => $proxy_set_header,
    fastcgi                     => $fastcgi,
    fastcgi_param               => $fastcgi_param,
    fastcgi_params              => $fastcgi_params,
    fastcgi_script              => $fastcgi_script,
    fastcgi_split_path          => $fastcgi_split_path,
    ssl                         => $ssl,
    ssl_only                    => $ssl_only,
    location_alias              => $location_alias,
    location_allow              => $location_allow,
    location_deny               => $location_deny,
    option                      => $option,
    stub_status                 => $stub_status,
    raw_prepend                 => $raw_prepend,
    raw_append                  => $raw_append,
    location_custom_cfg         => $location_custom_cfg,
    location_cfg_prepend        => $location_cfg_prepend,
    location_cfg_append         => $location_cfg_append,
    location_custom_cfg_prepend => $location_custom_cfg_prepend,
    location_custom_cfg_append  => $location_custom_cfg_append,
    try_files                   => $try_files,
    proxy_cache                 => $proxy_cache,
    proxy_cache_valid           => $proxy_cache_valid,
    proxy_method                => $proxy_method,
    proxy_set_body              => $proxy_set_body,
    auth_basic                  => $auth_basic,
    auth_basic_user_file        => $auth_basic_user_file,
    rewrite_rules               => $rewrite_rules,
    priority                    => $priority,
    mp4                         => $mp4,
    flv                         => $flv,
  }
}
